---
- name: "Installing desktop environments"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - lightdm
    - lxde
    - lxsession
    - x2goclient
    - kde-plasma-desktop
    - xserver-xorg-core
  when: basesystem_task_desktop == true

