---
- name: "Installing development utils"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - autoconf
    - automake
    - build-essential
    - cmake
    - configure-debian
    - devscripts
    - git-core
    - git-flow
    - hg-fast-export
    - libtool
    - meld
    - mercurial
    - opam
    - screen
    - subversion
    - tmux
    - vim
    - vim-gtk
    - kate
    - kdevelop
    - umbrello
    - umlet
    - xutils
    - curl 
    - mercurial 
    - make 
    - binutils 
    - bison 
    - gcc-5
    - gcc-5-multilib
    - clang-3.8

- name: "Installing Ruby language"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - gem2deb

- name: "Installing php5 language"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - virtualenv

- name: "Installing Rust language"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - rustc
    - rust-doc
    - rust-gdb
    - cargo

- name: "Installing Go language"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - golang

- name: "Installing PHP language"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - php5-apcu
    - php5-cli
    - php5-common
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-json
    - php5-mcrypt
    - php5-mysql
    - php5-readline
    - php5-tidy
    - php5-xsl

- name: "Installing development libraries"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - libdrm-dev
    - libreadline-dev
    - libssl-dev
    - manpages-dev
    - mesa-common-dev
    - plasma-desktop-dev
    - xorg-dev
    - xserver-xorg-dev
    - xutils-dev
    - libsqlite3-dev
    - libsqlite0-dev

