---
- name: "Installing system development utils"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - manpages-dev
    - cmake
    - configure-debian
    - git-core
    - git-flow
    - mercurial
    - hg-fast-export
    - meld
    - mercurial
    - screen
    - subversion
    - tmux
    - vim
    - curl 
    - mercurial 
  when: basesystem_task_development == true

- name: "Installing C/C++ development utils"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - autoconf  
    - automake
    - build-essential
    - cmake
    - configure-debian
    - devscripts
    - libtool
    - make 
    - binutils 
    - bison 
    - gcc
    - gcc-multilib
  when: basesystem_task_development == true
  #  - clang

- name: "Installing desktop development utils"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - umbrello
    - umlet
    - kdevelop
    - vim-gtk
    - kate
    - xutils
  when: (basesystem_task_development == true) and (basesystem_task_desktop == true)

- name: "Installing OCaml language"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - opam
  when: basesystem_task_development == true

- name: "Installing Haskell language"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - ghc
    - libghc-uuid-dev 
    - libghc-uuid-types-dev
    - libghc-configfile-dev 
    - libghc-path-dev 
    - libghc-ghc-paths-dev 
    - libghc-system-fileio-dev
    - libghc-path-pieces-dev
    - libghc-glob-dev
    - libghc-json-dev
    - libghc-pandoc-dev
    - libghc-hoauth2-dev 
    - libghc-feed-dev
    - libghc-filestore-dev
    - libghc-xss-sanitize-dev
    - libghc-recaptcha-dev
    - libghc-happstack-server-dev
    - libghc-hstringtemplate-dev
    - libghc-safe-dev
    - libghc-uri-dev
    - libghc-url-dev
  when: basesystem_task_development == true

- name: "Installing Ruby language"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - gem2deb
  when: basesystem_task_development == true

- name: "Installing php5 language"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - virtualenv
  when: basesystem_task_development == true

- name: "Installing Rust language"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - rustc
    - rust-doc
    - rust-gdb
    - cargo
  when: basesystem_task_development == true

- name: "Installing Go language"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - golang
  when: basesystem_task_development == true

- name: "Installing PHP language"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - php5-apcu
    - php5-cli
    - php5-common
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-json
    - php5-mcrypt
    - php5-mysql
    - php5-readline
    - php5-tidy
    - php5-xsl
  when: basesystem_task_development == true

- name: "Installing development libraries"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - libdrm-dev
    - libreadline-dev
    - libssl-dev
    - manpages-dev
    - mesa-common-dev
    - plasma-desktop-dev
    - xorg-dev
    - xserver-xorg-dev
    - xutils-dev
    - libsqlite3-dev
    - libsqlite0-dev
  when: basesystem_task_development == true

