---

## FIXME: check that default values are sane, or fail
- fail: msg="Please set basesystem_arch value to something ..."
  when: basesystem_arch is undefined

- fail: msg="Please set basesystem_task_desktop to either true or false"
  when: basesystem_task_desktop is undefined

- fail: msg="Please set basesystem_task_development to either true or false"
  when: basesystem_task_development is undefined

- fail: msg="Please set basesystem_task_multimedia to either true or false"
  when: basesystem_task_multimedia is undefined

- fail: msg="Please set basesystem_task_network to either true or false"
  when: basesystem_task_network is undefined

- fail: msg="Please set basesystem_task_office to either true or false"
  when: basesystem_task_office is undefined

- fail: msg="Please set basesystem_task_security to either true or false"
  when: basesystem_task_security is undefined

- fail: msg="Please set basesystem_task_shell to either true or false"
  when: basesystem_task_shell is undefined

- fail: msg="Please set basesystem_task_shopping to either true or false"
  when: basesystem_task_shopping is undefined

- fail: msg="Please set basesystem_task_system to either true or false"
  when: basesystem_task_system is undefined

- template: 
    src=apt_conf_glenuxnet_base.j2
    dest=/etc/apt/apt.conf.d/00glenuxnet_base
    owner=root
    group=root
    mode=0644

# Debian normal
- apt_repository: repo='deb http://ftp.fr.debian.org/debian/ stable main contrib non-free' state=present
- apt_repository: repo='deb-src http://ftp.fr.debian.org/debian/ stable main contrib non-free' state=present

- apt_repository: repo='deb http://ftp.fr.debian.org/debian/ testing main contrib non-free' state=present
- apt_repository: repo='deb-src http://ftp.fr.debian.org/debian/ testing main contrib non-free' state=present

- apt_repository: repo='deb http://ftp.fr.debian.org/debian/ unstable main contrib non-free' state=present
- apt_repository: repo='deb-src http://ftp.fr.debian.org/debian/ unstable main contrib non-free' state=present

- apt_repository: repo='deb http://ftp.fr.debian.org/debian/ experimental main contrib non-free' state=present
- apt_repository: repo='deb-src http://ftp.fr.debian.org/debian/ experimental main contrib non-free' state=present

# Debian security
- apt_repository: repo='deb http://security.debian.org/ stable/updates main contrib non-free' state=present
- apt_repository: repo='deb-src http://security.debian.org/ stable/updates main contrib non-free' state=present

# Debian stable-update (ex-volatile)
- apt_repository: repo='deb http://ftp.fr.debian.org/debian/ stable-updates main contrib non-free' state=present
- apt_repository: repo='deb-src http://ftp.fr.debian.org/debian/ stable-updates main contrib non-free' state=present

- command: /bin/true
  notify: ['Update APT cache']

- include: system.yml
- include: desktop.yml
- include: shopping.yml
- include: multimedia.yml
- include: development.yml
- include: network.yml
- include: security.yml
- include: shell.yml

