---
# tasks file for glenux.basesystem
- name: "Installing desktop environments"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - lightdm
    - lxde
    - lxsession
    - x2goclient
    - kde-plasma-desktop
    - xserver-xorg-core

- name: "Installing development utils"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - vim
    - vim-gtk
    - git
    - git-flow
    - subversion
    - mercurial
    - hg-fast-export
    - meld
    - devscripts
    - screen
    - tmux
    - opam
    - cmake

- name: "Installing development utils"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - manpages-dev
    - plasma-desktop-dev
    - xserver-xorg-dev

- name: "Installing common office tools"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - leafpad
    - libreoffice
    - lyx
    - ttf-mscorefonts-installer

- name: "Installing drawing utils"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - gimp
    - geeqie
    - gwenview
    - inkscape

- name: "Installing common video tools"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - mpv
    - mplayer
    - vlc
    - transcode

- name: "Installing common communication tools"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - iceweasel
    - icedove
    - chromium
    - psi-plus
    - mutt

- name: "Installing common security tools"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - encfs
    - cryptkeeper
    - cryptmount
    - cryptsetup
    - cryptsetup-bin
    - libpam-encfs
    - keepassx
    - kpcli
    - pwgen
    - openvpn
    - network-manager-openvpn
    - easy-rsa

- name: "Installing expert network tools"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - nmap
    - wireshark
    - manpages-dev
    - vlan

- name: "Installing system utils"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - htop
    - unrar

