---
- name: "Installing desktop multimedia tools"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - transcode
    - ffmpeg
  when: basesystem_task_multimedia == true

- name: "Installing desktop multimedia tools"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - mpv
    - mplayer
    - vlc
    - flashplugin-nonfree
    - pepperflashplugin-nonfree
  when: basesystem_task_multimedia == true && basesystem_task_desktop == true

