---
- name: "Installing office/text utils"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - leafpad
    - libreoffice
    - lyx
    - ttf-mscorefonts-installer
  when: basesystem_task_desktop == true && basesystem_task_office == true

- name: "Installing office/image utils"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - gimp
    - geeqie
    - gwenview
    - inkscape
    - okular
  when: basesystem_task_desktop == true && basesystem_task_office == true

- name: "Installing office/communication tools"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - iceweasel
    - icedove
    - chromium
    - psi-plus
    - mutt
  when: basesystem_task_desktop == true && basesystem_task_office == true

