---
- name: "Installing system security tools"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - bruteforce-luks # system & security 
    - encfs  # system & security
    - encfs  # system & security
    - cryptsetup # system & security
    - cryptsetup-bin # system & security
    - libpam-encfs # system & security
    - openvpn # system or desktop and security
    - easy-rsa # system & security
  when: basesystem_task_security == true

- name: "Installing desktop security tools"
  apt: >
    name="{{item}}"
    state=present
  with_items:
    - cryptkeeper # desktop & security
    - cryptmount # desktop & security
    - network-manager-openvpn # desktop & security
    - keepassx # desktop & security
    - kpcli # desktop ?? & security
    - pwgen # desktop & security
  when: (basesystem_task_desktop == true) and (basesystem_task_security == true)

